In [ ]:
# Task 1
total_cards = 52
red_cards = 26               
hearts = 13
diamonds = 13
face_cards_total = 12        
face_diamonds = 3            
face_spades = 3              
face_queens = 4              
face_spade_or_queen = face_spades + face_queens - 1  

p_red = red_cards / total_cards

p_heart_given_red = hearts / red_cards

p_diamond_given_face = face_diamonds / face_cards_total

p_spade_or_queen_given_face = face_spade_or_queen / face_cards_total

print(f"P(Red) = {p_red} = {red_cards}/{total_cards}")
print(f"P(Heart | Red) = {p_heart_given_red} = {hearts}/{red_cards}")
print(f"P(Diamond | Face) = {p_diamond_given_face} = {face_diamonds}/{face_cards_total}")
print(
    f"P(Spade or Queen | Face) = {p_spade_or_queen_given_face} = "
    f"{face_spade_or_queen}/{face_cards_total}"
)


In [ ]:
# Task 2
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import VariableElimination

model = DiscreteBayesianNetwork([
    ('Intelligence', 'Grade'),
    ('StudyHours', 'Grade'),
    ('Difficulty', 'Grade'),
    ('Grade', 'Pass')
])

print("Bayesian Network Structure Diagram:")
print("Intelligence -> Grade <- StudyHours")
print("Difficulty   -> Grade -> Pass")
print("Edges:", list(model.edges()))

cpd_intelligence = TabularCPD(
    variable='Intelligence',
    variable_card=2,
    values=[[0.7], [0.3]],
    state_names={'Intelligence': ['High', 'Low']}
)

cpd_study = TabularCPD(
    variable='StudyHours',
    variable_card=2,
    values=[[0.6], [0.4]],
    state_names={'StudyHours': ['Sufficient', 'Insufficient']}
)

cpd_difficulty = TabularCPD(
    variable='Difficulty',
    variable_card=2,
    values=[[0.4], [0.6]],
    state_names={'Difficulty': ['Hard', 'Easy']}
)

cpd_grade = TabularCPD(
    variable='Grade',
    variable_card=3,
    values=[
        [0.75, 0.90, 0.45, 0.60, 0.40, 0.55, 0.10, 0.20],  # Grade = A
        [0.20, 0.08, 0.35, 0.30, 0.40, 0.30, 0.30, 0.30],  # Grade = B
        [0.05, 0.02, 0.20, 0.10, 0.20, 0.15, 0.60, 0.50]   # Grade = C
    ],
    evidence=['Intelligence', 'StudyHours', 'Difficulty'],
    evidence_card=[2, 2, 2],
    state_names={
        'Grade': ['A', 'B', 'C'],
        'Intelligence': ['High', 'Low'],
        'StudyHours': ['Sufficient', 'Insufficient'],
        'Difficulty': ['Hard', 'Easy']
    }
)

cpd_pass = TabularCPD(
    variable='Pass',
    variable_card=2,
    values=[
        [0.05, 0.20, 0.50],
        [0.95, 0.80, 0.50]
    ],
    evidence=['Grade'],
    evidence_card=[3],
    state_names={
        'Pass': ['No', 'Yes'],
        'Grade': ['A', 'B', 'C']
    }
)

model.add_cpds(cpd_intelligence, cpd_study, cpd_difficulty, cpd_grade, cpd_pass)
assert model.check_model()

print("\nAll CPTs added successfully.")
print("P(Intelligence):")
print(cpd_intelligence)
print("\nP(StudyHours):")
print(cpd_study)
print("\nP(Difficulty):")
print(cpd_difficulty)
print("\nP(Grade | Intelligence, StudyHours, Difficulty):")
print(cpd_grade)
print("\nP(Pass | Grade):")
print(cpd_pass)

infer = VariableElimination(model)

q_pass = infer.query(
    variables=['Pass'],
    evidence={'StudyHours': 'Sufficient', 'Difficulty': 'Hard'}
)

q_intelligence = infer.query(
    variables=['Intelligence'],
    evidence={'Pass': 'Yes'}
)

p_pass_yes = q_pass.get_value(Pass='Yes')
p_int_high_given_pass = q_intelligence.get_value(Intelligence='High')

print("\nInference Results:")
print("P(Pass | StudyHours=Sufficient, Difficulty=Hard):")
print(q_pass)
print("\nProbability of passing (Yes):", p_pass_yes)

print("\nP(Intelligence | Pass=Yes):")
print(q_intelligence)
print("\nProbability of High Intelligence given Pass=Yes:", p_int_high_given_pass)

In [ ]:
# Task 3
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import VariableElimination

model_task3 = DiscreteBayesianNetwork([
    ('Disease', 'Fever'),
    ('Disease', 'Cough'),
    ('Disease', 'Fatigue'),
    ('Disease', 'Chills')
])

print('Bayesian Network Structure Diagram:')
print('Disease -> Fever')
print('Disease -> Cough')
print('Disease -> Fatigue')
print('Disease -> Chills')
print('Edges:', list(model_task3.edges()))

cpd_disease = TabularCPD(
    variable='Disease',
    variable_card=2,
    values=[[0.3], [0.7]],
    state_names={'Disease': ['Flu', 'Cold']}
)

cpd_fever = TabularCPD(
    variable='Fever',
    variable_card=2,
    values=[[0.9, 0.5], [0.1, 0.5]],
    evidence=['Disease'],
    evidence_card=[2],
    state_names={'Fever': ['Yes', 'No'], 'Disease': ['Flu', 'Cold']}
)

cpd_cough = TabularCPD(
    variable='Cough',
    variable_card=2,
    values=[[0.8, 0.6], [0.2, 0.4]],
    evidence=['Disease'],
    evidence_card=[2],
    state_names={'Cough': ['Yes', 'No'], 'Disease': ['Flu', 'Cold']}
)

cpd_fatigue = TabularCPD(
    variable='Fatigue',
    variable_card=2,
    values=[[0.7, 0.3], [0.3, 0.7]],
    evidence=['Disease'],
    evidence_card=[2],
    state_names={'Fatigue': ['Yes', 'No'], 'Disease': ['Flu', 'Cold']}
)

cpd_chills = TabularCPD(
    variable='Chills',
    variable_card=2,
    values=[[0.6, 0.4], [0.4, 0.6]],
    evidence=['Disease'],
    evidence_card=[2],
    state_names={'Chills': ['Yes', 'No'], 'Disease': ['Flu', 'Cold']}
)

model_task3.add_cpds(cpd_disease, cpd_fever, cpd_cough, cpd_fatigue, cpd_chills)
assert model_task3.check_model()

print('\nCPTs:')
print(cpd_disease)
print(cpd_fever)
print(cpd_cough)
print(cpd_fatigue)
print(cpd_chills)

infer_task3 = VariableElimination(model_task3)

q_disease_fc = infer_task3.query(
    variables=['Disease'],
    evidence={'Fever': 'Yes', 'Cough': 'Yes'}
)

q_disease_fcc = infer_task3.query(
    variables=['Disease'],
    evidence={'Fever': 'Yes', 'Cough': 'Yes', 'Chills': 'Yes'}
)

p_fatigue_yes_given_flu = infer_task3.query(
    variables=['Fatigue'],
    evidence={'Disease': 'Flu'}
).get_value(Fatigue='Yes')

print('\nInference Task 1: P(Disease | Fever=Yes, Cough=Yes)')
print(q_disease_fc)
print('P(Flu | Fever=Yes, Cough=Yes):', q_disease_fc.get_value(Disease='Flu'))
print('P(Cold | Fever=Yes, Cough=Yes):', q_disease_fc.get_value(Disease='Cold'))

print('\nInference Task 2: P(Disease | Fever=Yes, Cough=Yes, Chills=Yes)')
print(q_disease_fcc)
print('P(Flu | Fever=Yes, Cough=Yes, Chills=Yes):', q_disease_fcc.get_value(Disease='Flu'))
print('P(Cold | Fever=Yes, Cough=Yes, Chills=Yes):', q_disease_fcc.get_value(Disease='Cold'))

print('\nInference Task 3: P(Fatigue=Yes | Disease=Flu)')
print('P(Fatigue=Yes | Disease=Flu):', p_fatigue_yes_given_flu)

In [17]:
# Task 4
import numpy as np

states = ['Sunny', 'Cloudy', 'Rainy']
state_to_idx = {state: i for i, state in enumerate(states)}

transition_matrix = np.array([
    [0.6, 0.3, 0.1],
    [0.3, 0.4, 0.3],
    [0.2, 0.5, 0.3]
])

print('States:', states)
print('Transition Matrix (rows=current, cols=next):')
print(transition_matrix)
print('Row sums:', transition_matrix.sum(axis=1))

rng = np.random.default_rng(42)
days = 10
weather_sequence = ['Sunny']

for _ in range(days - 1):
    current_state = weather_sequence[-1]
    current_idx = state_to_idx[current_state]
    next_state = str(rng.choice(states, p=transition_matrix[current_idx]))
    weather_sequence.append(next_state)

rainy_days_simulated = sum(1 for day in weather_sequence if day == 'Rainy')

print('\nSimulated weather for 10 days (start=Sunny):')
print(weather_sequence)
print('Rainy days in this simulation:', rainy_days_simulated)

dp = np.zeros((days, days + 1, len(states)))
dp[0, 0, state_to_idx['Sunny']] = 1.0

for day in range(1, days):
    for rainy_count in range(day + 1):
        for prev_state_idx in range(len(states)):
            prev_prob = dp[day - 1, rainy_count, prev_state_idx]
            if prev_prob == 0:
                continue
            for next_state_idx in range(len(states)):
                next_prob = transition_matrix[prev_state_idx, next_state_idx]
                new_rainy_count = rainy_count + (1 if states[next_state_idx] == 'Rainy' else 0)
                dp[day, new_rainy_count, next_state_idx] += prev_prob * next_prob

prob_at_least_3_rainy = dp[days - 1, 3:, :].sum()

print('\nProbability of at least 3 rainy days in 10 days (starting Sunny):')
print(prob_at_least_3_rainy)

States: ['Sunny', 'Cloudy', 'Rainy']
Transition Matrix (rows=current, cols=next):
[[0.6 0.3 0.1]
 [0.3 0.4 0.3]
 [0.2 0.5 0.3]]
Row sums: [1. 1. 1.]

Simulated weather for 10 days (start=Sunny):
['Sunny', 'Cloudy', 'Cloudy', 'Rainy', 'Cloudy', 'Sunny', 'Rainy', 'Rainy', 'Rainy', 'Sunny']
Rainy days in this simulation: 4

Probability of at least 3 rainy days in 10 days (starting Sunny):
0.28194415
